apiVersion: v1
kind: Service
metadata:
  name: multi-tenant-api
spec:
  selector:
    app: multi-tenant-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
    - protocol: TCP
      port: 8081
      targetPort: 443
  type: LoadBalancer